---
title: "Generate computational grids"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Generate computational grids}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```


## Prepare input data
```{r}
library(chopin)
library(sf)
library(terra)
library(stars)
library(dplyr)

```

## Computational grids
```{r}
library(chopin)
library(dplyr)
library(sf)
library(terra)
options(sf_use_s2 = FALSE)
```

```{r}
ncpoly <- system.file("shape/nc.shp", package = "sf")
ncsf <- sf::read_sf(ncpoly)
ncsf <- sf::st_transform(ncsf, "EPSG:5070")
plot(sf::st_geometry(ncsf))
```

```{r}
ncpoints <- sf::st_sample(ncsf, 10000)
plot(sf::st_geometry(ncpoints))

# st_sample output is st_sfc. We should convert it to sf
ncpoints <- st_as_sf(ncpoints)
ncpoints$pid <- seq(1, nrow(ncpoints))
```


## Visualize computational grids

```{r}
ncpoints_tr <- terra::vect(ncpoints)
compregions <-
    chopin::get_computational_regions(
        ncpoints_tr,
        mode = "grid",
        nx = 8L,
        ny = 5L,
        padding = 1e4L
    )

names(compregions)

par(mfcol = c(1, 2))
plot(compregions$original, main = "Original grids")
plot(compregions$padded, main = "Padded grids")
```




## Notes
- Computational grids are the exhaustive split of the entire study region. You should take a square buffer of each grid to clip the target raster or vector.
